name: tripitaka91
description: พระไตรปิฎกและอรรถกถาแปล ชุด 91 เล่ม ฉบับ มมร. (เล่มสีน้ำเงิน)
publish_to: 'none' 
version: 4.0.0+22
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  simple_html_css: ^4.0.0
  hexcolor: ^3.0.1
  substring_highlight: ^1.0.33 
  intl: ^0.19.0
  just_audio: ^0.9.36
  provider: ^6.1.1
  path_provider: ^2.1.4
  share_plus: ^7.2.1
  just_audio_windows: ^0.2.0
  url_launcher: ^6.2.5
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.1
  screenshot: ^2.5.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.1  

flutter:  
  uses-material-design: true
  assets:
     - assets/images/
     - assets/images/bookcover/
     - assets/images/ebook/     
     - assets/images/title/
     - assets/fonts/
     - assets/pdf/
     - assets/db/
     - assets/fonts/CupertinoIcons.ttf
     - assets/fonts/MaterialIcons-Regular.otf
     - assets/web/web_support.js
  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto.ttf
        weight: 300
      - asset: assets/fonts/Roboto.ttf
        weight: 400
      - asset: assets/fonts/Roboto.ttf
        style: italic
      - asset: assets/fonts/Roboto.ttf
        weight: 500
      - asset: assets/fonts/Roboto.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Roboto.ttf
        weight: 600
      - asset: assets/fonts/Roboto.ttf
        weight: 800
  # - family: Roboto
  #   fonts:
  #     - asset: assets/fonts/Roboto.ttf
  - family: THSarabunNew
    fonts:
      - asset: assets/fonts/THSarabunNew.ttf
  - family: THSarabunNewItalic
    fonts:
      - asset: assets/fonts/THSarabunNewItalic.ttf
  - family: THSarabunNewBold
    fonts:
      - asset: assets/fonts/THSarabunNewBold.ttf
  - family: THSarabunNewBoldItalic
    fonts:
      - asset: assets/fonts/THSarabunNewBoldItalic.ttf  
  
  - family: NotoSans
    fonts:
      - asset: assets/fonts/NotoSansThai-Regular.ttf  
  
  - family: MaterialIcons
    fonts:
      - asset: assets/fonts/MaterialIcons-Regular.otf     
  
  - family: CupertinoIcons
    fonts:
      - asset: assets/fonts/CupertinoIcons.ttf     